### ISSUE TITLE
Not working with ReactJS

### ISSUE THREAD

**Issue by annelorraineuy** [kleinejan/titatoggle#12]
Hello. I've included the titatoggle-dist.css into my ReactJS project but the toggle doesn't seem to be working (looks disabled). Is there something I may be doing wrong? 

`<div className="checkbox checkbox-slider--b-flat checkbox-slider-warning"><input type="checkbox" /><span></span></div>`

**Comment by kleinejan** [comment]
"<div className=" Should be "<div class=" :)

**Comment by annelorraineuy** [comment]
Sorry for the late response, but it was `className` because that is ReactJS code.

**Comment by kleinejan** [comment]
Ah Okay, but you got it working again? ;)
