### ISSUE TITLE
checked and unchecked via JS

### ISSUE THREAD

**Issue by sera2007** [kleinejan/titatoggle#26]
Hi there, Thanks for your work! It's great and so simple solution!

But I have one problem - it's checking and unchecking the styled checkbox via JS. Here is the demo http://take.ms/ysu1S , I can't set checked attribute to the styled checkbox. Do you have any ideas here?

**Comment by fdrcslv** [comment]
Hi, I had the same problem as @sera2007  but I found the solution. 
You have to select the inputs of your checkboxes and set the checked property unsing Jquery's [prop](http://api.jquery.com/prop/).

`$('.checkbox').find('input').prop('checked', true)`

if you want to check/uncheck only some of your checkboxes just add a class!
hope this helps!
