### ISSUE TITLE
checkbox-slider--c and checkbox-slider--c-weight look the same

### ISSUE THREAD

**Issue by gwhenne** [kleinejan/titatoggle#36]
Have a look at this page. There seems to be no difference.
https://kleinejan.github.io/titatoggle/

![screen shot 2018-07-28 at 8 50 22 am](https://user-images.githubusercontent.com/489708/43356691-4f9ca31a-9243-11e8-9bb8-44ae0015e317.png)

**Comment by kleinejan** [comment]
Have a close look at the circle. It varies in weight. Checked : larger green dot

**Comment by gwhenne** [comment]
Thanks - I see what you mean.
