### ISSUE TITLE
Allow customized On/Off text

### ISSUE THREAD

**Issue by jorvis** [kleinejan/titatoggle#37]
I'd love to be able to toggle between states like "absolute/relative" what that text currently within the toggle where the "On/Off" text currently lives. Is there a way to customize this?

**Comment by DCarterAJLA** [comment]
Yes You can override the content value of the sliders like this:

`

    .checkbox-slider--a input + span:after {
      content: "No";
    }

    .checkbox-slider--a input:checked + span:after {
      content: "Yes";
    }
`

**Comment by kleinejan** [comment]
Fixed in new version
