### ISSUE TITLE
Check license

### ISSUE THREAD

**Issue by pvnr0082t** [kleinejan/titatoggle#9]
Hi @kleinejan ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this library on cdnjs.
I found that license in package.json show `BSD-2-Clause` but there is [GNU-General-Public-License-v2.0.txt](https://github.com/kleinejan/titatoggle/blob/master/GNU-General-Public-License-v2.0.txt) in the repo. Could you please help me check which license used for the repo? Thanks.

https://github.com/cdnjs/cdnjs/issues/7859
https://github.com/cdnjs/cdnjs/pull/8064

**Comment by PeterDaveHello** [comment]
He may just forget to update package.json.

**Comment by kleinejan** [comment]
correct! and it is updated now

**Comment by pvnr0082t** [comment]
@kleinejan Thanks! :+1:
